---
title: "Simulations tables"
author: "Andreas Olden"
date: "January 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}

#Initiate project
library(checkpoint) #Checkpoint assures us that we use the same package versions
checkpoint("2019-01-21") #As they were at the date set in this function. i.e "2019-01-21"
library(here) # allows us to use relative file paths, see readme or simulations doc
library(stargazer) # To create tables
library(tidyverse) # Tidyverse data wrangling tool to use pipe-operator
library(DT) # A Wrapper of the JavaScript Library 'DataTables'
```

This is a Mardown document, cheat sheet: <https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf>
Tables using DT <https://rstudio.github.io/DT/>

```{r table_function}

html_table <- function(file, cust_cap){
        readRDS( here("results", file) ) %>% 
            gather(key="variable",value=value) %>% 
            group_by(variable) %>% 
            summarise(mean=mean(value,na.rm=T),
                      sd=sd(value,na.rm=T),
                      min=min(value, na.rm=T),
                      max=max(value, na.rm=T) ) %>% 
            datatable(rownames = FALSE, 
                      caption = cust_cap) %>%
            formatRound(columns=c("mean","sd", "min", "max"),digits=3)        
}

```

##Summary tables of simulation results

####Table 1
```{r simres1, echo=FALSE}
html_table(file = "simres1.rds", cust_cap = "One variable, alfa(-1.8,-1.5), beta(-0.02), xval(0), xsd(12.3)")
```

####Table 2

```{r simres2, echo=FALSE}
html_table(file = "simres2.rds", cust_cap = "#One variable, changed alfa1: alfa(-3,-1.5). This is 200% diff instead of 20%")
```

####Table 3

```{r simres3, echo=FALSE}
html_table(file = "simres3.rds", cust_cap = "One variable, changed standard dev of x-var (123 instead of 12.3)")
```

####Table 4

```{r simres4, echo=FALSE}
html_table(file = "simres4.rds", cust_cap = "Two variables, alfa(-1.8,-1.5), beta(-0.02, 0.2), xval(0), xsd(12.3, 1.8), corr(0)")
```

####Table 5

```{r simres5, echo=FALSE}
html_table(file = "simres5.rds", cust_cap = "Two variables, introduce 0.5 correlation between x's")
```

####Table 6

```{r simres6, echo=FALSE}
html_table(file = "simres6.rds", cust_cap = "Two variables, introduce 0.9 correlation between x's")
```

####Table 7

```{r simres7, echo=FALSE}
html_table(file = "simres7.rds", cust_cap = "Two variables, same as base but with sd*10 for X1 only")
```

####Table 8

```{r simres8, echo=FALSE}
html_table(file = "simres8.rds", cust_cap = "Two variables, same as base but with sd*10 for X1 AND X2")
```

####Table 9

```{r simres9, echo=FALSE}
html_table(file = "simres9.rds", cust_cap = "Two variables, same as base but with sd*10 for X1 AND X2 AND CORR(0.9)")
```

####Table 10

```{r simres10, echo=FALSE}
html_table(file = "simres10.rds", cust_cap = "Three var Caudill non-zero mean and correlation")
```





